### ISSUE TITLE
The device activity graph x axis should be ordered by hour+

### ISSUE THREAD

**Issue by rogeriobiondi** [meccano-iot/webconsole#70]
The activity graph x axis shows the hour and y the number of updates the device has sent. The x axis is random and should be ordered by the hour in an ascending way, such as 9h, 10h, 11h, 12h, 13.. and so on.

**Comment by rogeriobiondi** [comment]
Took a look at the console and seems to be fixed. Let's wait and check during the day and we may close this issue in a few hours.

**Comment by diegofernandes** [comment]
yeah, i did a fix on PR #72. @matheuspupo is doing a new release.
